### ISSUE TITLE
fix posts links

### ISSUE THREAD

**Issue by MarioCodes** [MarioCodes/mariocodes.github.io#56]
See: https://jekyllrb.com/docs/liquid/tags/#linking-to-posts  

Until now I've included an absolute URL when linking to another posts. This means they break in development.  

I've now learnt there's a way to link to posts in jekyll. This won't break between prod and dev environments. 
- [x] check and fix all posts which include links
- [x] test in local
- [x] test in prod

**Comment by MarioCodes** [comment]
Check for dead URLs with `htmlproofer`

**Comment by MarioCodes** [comment]
Found and fixed the one of them which were broken. I don't know if there are more though.

**Comment by MarioCodes** [comment]
moved images to my GCP bucket
